# Generated by Django 5.0.3 on 2024-03-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_address_alter_usermodel_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='profile_picture',
        ),
    ]
